#!/bin/bash
#
# Copyright(c) 2012-2019 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause-Clear
#

VER_FILE=CAS_VERSION

if [ -f ${VER_FILE} ]; then
	echo "Using existing ${VER_FILE} version file."
	echo ""
    exit 0
else
	echo "No ${VER_FILE} found. Preparing default version file."
	echo ""

	CAS_VERSION_MAIN=20
	CAS_VERSION_MAJOR=1
	CAS_VERSION_MINOR=0
	CAS_BUILD_NO=0000`date +%m%d`

	touch ${VER_FILE}

fi

CAS_VERSION=$(printf "%02d.%02d.%02d.%s" $CAS_VERSION_MAIN $CAS_VERSION_MAJOR \
        $CAS_VERSION_MINOR $CAS_BUILD_NO)

echo "CAS_VERSION_MAIN=${CAS_VERSION_MAIN}" >> ${VER_FILE}
echo "CAS_VERSION_MAJOR=${CAS_VERSION_MAJOR}" >> ${VER_FILE}
echo "CAS_VERSION_MINOR=${CAS_VERSION_MINOR}" >> ${VER_FILE}
echo "CAS_VERSION=${CAS_VERSION}" >> ${VER_FILE}

cat ${VER_FILE}
