line-length = 100

[lint]
# TODO This is temporary workaround. Ruff 0.16 introduced a ton of new rules, which our code
# does not follow. To avoid a long list of errors that everyone ignores anyway, select only
# the rules that were present in the previous version. That way we still effectively enforce
# following those rules, while giving ourselves some time to gradually expand the rules list.
select = ["E4", "E7", "E9", "F"]
ignore = [
    "E402", # All module level imports should be at the top of the file. This means that there
            # should be no statements in between module level imports
    "F405", # Variable  may be undefined, or defined from star imports
]
