#!/bin/bash
#
# Copyright(c) 2026 Unvertical
# SPDX-License-Identifier: BSD-3-Clause
#

. $(dirname $3)/conf_framework.sh

check() {
	cur_name=$(basename $2)
	config_file_path=$1
	if compile_module $cur_name "blk_mq_freeze_queue_nomemsave(NULL);" "linux/blk-mq.h"
	then
		echo $cur_name "1" >> $config_file_path
	else
		echo $cur_name "2" >> $config_file_path
	fi
}

apply() {
	case "$1" in
	"1")
	add_function "
	static inline void cas_blk_mq_freeze_queue(struct request_queue *q)
	{
		blk_mq_freeze_queue_nomemsave(q);
	}
	static inline void cas_blk_mq_unfreeze_queue(struct request_queue *q)
	{
		blk_mq_unfreeze_queue_nomemrestore(q);
	}" ;;

	"2")
	add_function "
	static inline void cas_blk_mq_freeze_queue(struct request_queue *q)
	{
		blk_mq_freeze_queue(q);
	}
	static inline void cas_blk_mq_unfreeze_queue(struct request_queue *q)
	{
		blk_mq_unfreeze_queue(q);
	}" ;;
	*)
	exit 1
	esac
}

conf_run $@
