#!/bin/bash
#
# Copyright(c) 2026 Unvertical
# SPDX-License-Identifier: BSD-3-Clause
#

. $(dirname $3)/conf_framework.sh

check() {
	cur_name=$(basename $2)
	config_file_path=$1
	if compile_module $cur_name "submit_bio_noacct(NULL);" "linux/blkdev.h"
	then
		echo $cur_name "1" >> $config_file_path
	elif compile_module $cur_name "generic_make_request(NULL);" "linux/blkdev.h"
	then
		echo $cur_name "2" >> $config_file_path
    else
        echo $cur_name "X" >> $config_file_path
    fi
}

apply() {
    case "$1" in
    "1")
		add_function "
	static inline void cas_submit_bio_noacct(struct bio *bio)
	{
		submit_bio_noacct(bio);
	}" ;;

    "2")
		add_function "
	static inline void cas_submit_bio_noacct(struct bio *bio)
	{
		generic_make_request(bio);
	}" ;;
    *)
        exit 1
    esac
}

conf_run $@
