{
 "title": "Open CAS Linux",
 "description": "Dashboard for Open CAS Linux Prometheus exporter",
 "tags": [
  "opencas",
  "storage",
  "caching"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(opencas_cache_info, instance)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(opencas_cache_info{instance=~\"$nodename:.*\"}, instance)"
    }
   },
   {
    "name": "cache_id",
    "label": "Cache ID",
    "query": {
     "query": "label_values(opencas_cache_info{instance=~\"$node\"}, cache_id)"
    }
   },
   {
    "name": "core_id",
    "label": "Core ID",
    "query": {
     "query": "label_values(opencas_core_info{instance=~\"$node\", cache_id=~\"$cache_id\"}, core_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cache Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cache Instances",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(opencas_cache_info, \"type\", \"cache\", \"\", \"\"), \"id\", \"$1\", \"cache_id\", \"(.+)\"), \"disk\", \"$1\", \"short_path\", \"(.+)\"), \"status\", \"$1\", \"state\", \"(.+)\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(opencas_core_info, \"type\", \"core\", \"\", \"\"), \"id\", \"$1\", \"core_id\", \"(.+)\"), \"disk\", \"$1\", \"short_path\", \"(.+)\")"
    },
    {
     "expr": "label_replace(opencas_cache_line_size_bytes / 1024, \"id\", \"$1\", \"cache_id\", \"(.+)\")"
    },
    {
     "expr": "label_replace(opencas_cache_size_blocks * 4 / 1048576, \"id\", \"$1\", \"cache_id\", \"(.+)\")"
    },
    {
     "expr": "label_replace(opencas_core_seq_cutoff_threshold_bytes / 1024, \"id\", \"$1\", \"core_id\", \"(.+)\")"
    }
   ]
  },
  { "title": "Cache Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Cache Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(opencas_cache_usage_clean_blocks{cache_id=~\"$cache_id\"} / (opencas_cache_usage_occupancy_blocks{cache_id=~\"$cache_id\"} + opencas_cache_usage_free_blocks{cache_id=~\"$cache_id\"}), \"type\", \"clean\", \"\", \"\") or label_replace(-(opencas_cache_usage_dirty_blocks{cache_id=~\"$cache_id\"} / (opencas_cache_usage_occupancy_blocks{cache_id=~\"$cache_id\"} + opencas_cache_usage_free_blocks{cache_id=~\"$cache_id\"})), \"type\", \"dirty\", \"\", \"\")",
     "legendFormat": "Cache {{cache_id}} {{type}}"
    }
   ]
  },
  { "title": "Hit Ratio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(-(opencas_cache_requests_read_hits_total{cache_id=~\"$cache_id\"} / (opencas_cache_requests_read_total{cache_id=~\"$cache_id\"} + (opencas_cache_requests_read_total{cache_id=~\"$cache_id\"} == bool 0))), \"type\", \"read\", \"\", \"\") or label_replace(opencas_cache_requests_write_hits_total{cache_id=~\"$cache_id\"} / (opencas_cache_requests_write_total{cache_id=~\"$cache_id\"} + (opencas_cache_requests_write_total{cache_id=~\"$cache_id\"} == bool 0)), \"type\", \"write\", \"\", \"\")",
     "legendFormat": "Cache {{cache_id}} {{type}}"
    }
   ]
  },
  { "title": "Cache Request Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(-rate(opencas_cache_requests_read_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"reads\", \"\", \"\") or label_replace(rate(opencas_cache_requests_write_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"writes\", \"\", \"\")",
     "legendFormat": "Cache {{cache_id}} {{type}}"
    }
   ]
  },
  {
   "title": "Request Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(-rate(opencas_cache_requests_read_hits_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"read hits\", \"\", \"\") or label_replace(-rate(opencas_cache_requests_read_partial_misses_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"read partial misses\", \"\", \"\") or label_replace(-rate(opencas_cache_requests_read_full_misses_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"read full misses\", \"\", \"\") or label_replace(-rate(opencas_cache_requests_read_passthrough_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"read passthrough\", \"\", \"\") or label_replace(rate(opencas_cache_requests_write_hits_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"write hits\", \"\", \"\") or label_replace(rate(opencas_cache_requests_write_partial_misses_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"write partial misses\", \"\", \"\") or label_replace(rate(opencas_cache_requests_write_full_misses_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"write full misses\", \"\", \"\") or label_replace(rate(opencas_cache_requests_write_passthrough_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"write passthrough\", \"\", \"\")",
     "legendFormat": "Cache {{cache_id}} {{type}}"
    }
   ]
  },
  { "title": "Devices Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Cache Device Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(-rate(opencas_cache_blocks_cache_read_total{cache_id=~\"$cache_id\"}[$__rate_interval]) * 4096, \"type\", \"read\", \"\", \"\") or label_replace(rate(opencas_cache_blocks_cache_write_total{cache_id=~\"$cache_id\"}[$__rate_interval]) * 4096, \"type\", \"write\", \"\", \"\")",
     "legendFormat": "Cache {{cache_id}} {{type}}"
    }
   ]
  },
  {
   "title": "Core Device Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(-rate(opencas_core_blocks_core_read_total{cache_id=~\"$cache_id\"}[$__rate_interval]) * 4096, \"type\", \"read\", \"\", \"\") or label_replace(rate(opencas_core_blocks_core_write_total{cache_id=~\"$cache_id\"}[$__rate_interval]) * 4096, \"type\", \"write\", \"\", \"\")",
     "legendFormat": "Cache {{cache_id}} Core {{core_id}} {{type}}"
    }
   ]
  },
  {
   "title": "Exported Object Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(-rate(opencas_core_blocks_exported_read_total{cache_id=~\"$cache_id\"}[$__rate_interval]) * 4096, \"type\", \"read\", \"\", \"\") or label_replace(rate(opencas_core_blocks_exported_write_total{cache_id=~\"$cache_id\"}[$__rate_interval]) * 4096, \"type\", \"write\", \"\", \"\")",
     "legendFormat": "Cache {{cache_id}} Core {{core_id}} {{type}}"
    }
   ]
  },
  { "title": "Operations Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Pass-Through Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(-rate(opencas_cache_blocks_passthrough_read_total{cache_id=~\"$cache_id\"}[$__rate_interval]) * 4096, \"type\", \"read\", \"\", \"\") or label_replace(rate(opencas_cache_blocks_passthrough_write_total{cache_id=~\"$cache_id\"}[$__rate_interval]) * 4096, \"type\", \"write\", \"\", \"\")",
     "legendFormat": "Cache {{cache_id}} {{type}}"
    }
   ]
  },
  {
   "title": "Prefetch Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(-rate(opencas_cache_blocks_prefetch_core_read_readahead_total{cache_id=~\"$cache_id\"}[$__rate_interval]) * 4096, \"type\", \"core read\", \"\", \"\") or label_replace(rate(opencas_cache_blocks_prefetch_cache_write_readahead_total{cache_id=~\"$cache_id\"}[$__rate_interval]) * 4096, \"type\", \"cache write\", \"\", \"\")",
     "legendFormat": "Cache {{cache_id}} readahead {{type}}"
    }
   ]
  },
  {
   "title": "Cleaner Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(-rate(opencas_cache_blocks_cleaner_cache_read_total{cache_id=~\"$cache_id\"}[$__rate_interval]) * 4096, \"type\", \"cache read\", \"\", \"\") or label_replace(rate(opencas_cache_blocks_cleaner_core_write_total{cache_id=~\"$cache_id\"}[$__rate_interval]) * 4096, \"type\", \"core write\", \"\", \"\")",
     "legendFormat": "Cache {{cache_id}} {{type}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Cache Device Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(-rate(opencas_cache_errors_cache_read_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"read\", \"\", \"\") or label_replace(rate(opencas_cache_errors_cache_write_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"write\", \"\", \"\")",
     "legendFormat": "Cache {{cache_id}} {{type}}"
    }
   ]
  },
  {
   "title": "Core Device Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(-rate(opencas_cache_errors_core_read_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"read\", \"\", \"\") or label_replace(rate(opencas_cache_errors_core_write_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"write\", \"\", \"\")",
     "legendFormat": "Cache {{cache_id}} {{type}}"
    }
   ]
  },
  {
   "title": "Fallback Pass-Through Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(opencas_cache_fallback_pt_errors_total{cache_id=~\"$cache_id\"}[$__rate_interval])",
     "legendFormat": "Cache {{cache_id}} ({{short_path}})"
    }
   ]
  },
  {
   "title": "Total Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(opencas_cache_errors_total{cache_id=~\"$cache_id\"}[$__rate_interval])",
     "legendFormat": "Cache {{cache_id}} ({{short_path}})"
    }
   ]
  },
  {
   "title": "Core Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(opencas_core_usage_clean_blocks{cache_id=~\"$cache_id\", core_id=~\"$core_id\"} / on(cache_id) group_left() (opencas_cache_usage_occupancy_blocks{cache_id=~\"$cache_id\"} + opencas_cache_usage_free_blocks{cache_id=~\"$cache_id\"}), \"type\", \"clean\", \"\", \"\") or label_replace(-(opencas_core_usage_dirty_blocks{cache_id=~\"$cache_id\", core_id=~\"$core_id\"} / on(cache_id) group_left() (opencas_cache_usage_occupancy_blocks{cache_id=~\"$cache_id\"} + opencas_cache_usage_free_blocks{cache_id=~\"$cache_id\"})), \"type\", \"dirty\", \"\", \"\")",
       "legendFormat": "Cache {{cache_id}} Core {{core_id}} {{type}}"
      }
     ]
    },
    {
     "title": "Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(-(opencas_core_requests_read_hits_total{cache_id=~\"$cache_id\", core_id=~\"$core_id\"} / (opencas_core_requests_read_total{cache_id=~\"$cache_id\", core_id=~\"$core_id\"} + (opencas_core_requests_read_total{cache_id=~\"$cache_id\", core_id=~\"$core_id\"} == bool 0))), \"type\", \"read\", \"\", \"\") or label_replace(opencas_core_requests_write_hits_total{cache_id=~\"$cache_id\", core_id=~\"$core_id\"} / (opencas_core_requests_write_total{cache_id=~\"$cache_id\", core_id=~\"$core_id\"} + (opencas_core_requests_write_total{cache_id=~\"$cache_id\", core_id=~\"$core_id\"} == bool 0)), \"type\", \"write\", \"\", \"\")",
       "legendFormat": "Cache {{cache_id}} Core {{core_id}} {{type}}"
      }
     ]
    },
    {
     "title": "Core Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "label_replace(-rate(opencas_core_requests_read_total{cache_id=~\"$cache_id\", core_id=~\"$core_id\"}[$__rate_interval]), \"type\", \"reads\", \"\", \"\") or label_replace(rate(opencas_core_requests_write_total{cache_id=~\"$cache_id\", core_id=~\"$core_id\"}[$__rate_interval]), \"type\", \"writes\", \"\", \"\")",
       "legendFormat": "Cache {{cache_id}} Core {{core_id}} {{type}}"
      }
     ]
    },
    {
     "title": "Core Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "label_replace(-rate(opencas_core_errors_cache_total{cache_id=~\"$cache_id\", core_id=~\"$core_id\"}[$__rate_interval]), \"type\", \"cache errors\", \"\", \"\") or label_replace(rate(opencas_core_errors_core_total{cache_id=~\"$cache_id\", core_id=~\"$core_id\"}[$__rate_interval]), \"type\", \"core errors\", \"\", \"\")",
       "legendFormat": "Cache {{cache_id}} Core {{core_id}} {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IO Classes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO Class Configuration",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "opencas_ioclass_info{cache_id=~\"$cache_id\"}"
      }
     ]
    },
    {
     "title": "IO Class Cache Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(opencas_ioclass_usage_clean_blocks{cache_id=~\"$cache_id\"} / on(cache_id) group_left() (opencas_cache_usage_occupancy_blocks{cache_id=~\"$cache_id\"} + opencas_cache_usage_free_blocks{cache_id=~\"$cache_id\"}), \"type\", \"clean\", \"\", \"\") or label_replace(-(opencas_ioclass_usage_dirty_blocks{cache_id=~\"$cache_id\"} / on(cache_id) group_left() (opencas_cache_usage_occupancy_blocks{cache_id=~\"$cache_id\"} + opencas_cache_usage_free_blocks{cache_id=~\"$cache_id\"})), \"type\", \"dirty\", \"\", \"\")",
       "legendFormat": "Cache {{cache_id}} {{name}} ({{ioclass_id}}) {{type}}"
      }
     ]
    },
    {
     "title": "IO Class Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "label_replace(-rate(opencas_ioclass_requests_read_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"reads\", \"\", \"\") or label_replace(rate(opencas_ioclass_requests_write_total{cache_id=~\"$cache_id\"}[$__rate_interval]), \"type\", \"writes\", \"\", \"\")",
       "legendFormat": "Cache {{cache_id}} {{name}} ({{ioclass_id}}) {{type}}"
      }
     ]
    },
    {
     "title": "IO Class Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(-(opencas_ioclass_requests_read_hits_total{cache_id=~\"$cache_id\"} / (opencas_ioclass_requests_read_total{cache_id=~\"$cache_id\"} + (opencas_ioclass_requests_read_total{cache_id=~\"$cache_id\"} == bool 0))), \"type\", \"read\", \"\", \"\") or label_replace(opencas_ioclass_requests_write_hits_total{cache_id=~\"$cache_id\"} / (opencas_ioclass_requests_write_total{cache_id=~\"$cache_id\"} + (opencas_ioclass_requests_write_total{cache_id=~\"$cache_id\"} == bool 0)), \"type\", \"write\", \"\", \"\")",
       "legendFormat": "Cache {{cache_id}} {{name}} ({{ioclass_id}}) {{type}}"
      }
     ]
    }
   ]
  }
 ]
}