#!/bin/bash
#
# Copyright(c) 2012-2021 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#

# The line below specified that line under it should be used as the test's short description when launching test via run_tests script.
# The text should not be longer than 80 chars - if it is, the script will strip addititonal characters
# DESCRIPTION Verify cache and core read and write stats in WT in PT mode

# The line below says that this test should be included in BVT - it will be launched, when we use "./run_tests -b"

# Standard beginning for every test - get the main tests directory and
# link the cas_lib file for CAS API, then use "start_test $*" to pass params
# and do other necessary checks and setup.
TESTS_DIR="$(dirname $0)/../"
. $TESTS_DIR/cas_lib
start_test $*

CACHE_DEVICE_SIZE=1G
CORE_DEVICE_SIZE=10G
TEST_DEVICE=${DEVICE_NAME}1-1

#param device
get_stat_sectors_read() {
    L_DEVICE=$(basename $(realpath $1))
    L_STAT=$(cat /proc/diskstats | grep $L_DEVICE | awk '{ print $6 }')
    echo $L_STAT
}

#param device
get_stat_sectors_written() {
    L_DEVICE=$(basename $(realpath $1))
    L_STAT=$(cat /proc/diskstats | grep $L_DEVICE | awk '{ print $10 }')
    echo $L_STAT
}

cache_suspend_init() {
    # Use CACHE_DEVICE and CORE_DEVICE provided by configuration file and remove partitions from those devices
    TARGET_DEVICE_OPTION="$CACHE_DEVICE" remove_partitions
    TARGET_DEVICE_OPTION="$CORE_DEVICE" remove_partitions

    # Create 1 primary partitions on CACHE_DEVICE
    TARGET_DEVICE_OPTION="$CACHE_DEVICE" PARTITION_SIZE_OPTION=$CACHE_DEVICE_SIZE PARTITION_IDS_OPTION="1" make_primary_partitions

    # Create 1 primary partitions on CORE_DEVICE
    TARGET_DEVICE_OPTION="$CORE_DEVICE" PARTITION_SIZE_OPTION=$CORE_DEVICE_SIZE PARTITION_IDS_OPTION="1" make_primary_partitions

    run_cmd dd if=/dev/zero of="${CORE_DEVICE}-part1" bs=1M count=1 oflag=direct

    # Start cache on CACHE_DEVICE1
    CACHE_ID_OPTION="1" CACHE_DEVICE_OPTION="${CACHE_DEVICE}-part1" start_cache

    # Add a core device using CORE_DEVICE1
    CACHE_ID_OPTION="1" CORE_DEVICE_OPTION="${CORE_DEVICE}-part1" add_core
}

cache_suspend_deinit() {
    # Remove the core device from cache
    CACHE_ID_OPTION="1" CORE_ID_OPTION="1" remove_core

    # Clean up after the test
    CACHE_ID_OPTION="1" stop_cache
}

cache_suspend_test() {
    L_CACHE_READS_BEFORE=
    L_CACHE_READS_AFTER=
    L_CACHE_WRITES_BEFORE=
    L_CACHE_WRITES_AFTER=
    L_CORE_READS_BEFORE=
    L_CORE_READS_AFTER=

    # Write
    test_log_trace "Write 4k to be cached"
    dd if=/dev/urandom of=${TEST_DEVICE} bs=4k count=1 oflag=direct

    # Suspend the cache, flush dirty data.
    test_log_trace "Suspend Cache"
    CACHE_MODE_FLUSH_OPTION="yes" CACHE_ID_OPTION="1" CACHE_MODE_OPTION="pt" set_cache_mode

    # Get read cache statistics before.
    L_CACHE_READS_BEFORE=$(get_stat_sectors_read ${CACHE_DEVICE}-part1)

    # Read file
    test_log_trace "Read 4k, Read has to be performed from core"
    dd if=${TEST_DEVICE} of=/dev/null bs=4k count=1 iflag=direct

    # Sync
    sync && echo 3 > /proc/sys/vm/drop_caches

    L_CACHE_READS_AFTER=$(get_stat_sectors_read ${CACHE_DEVICE}-part1)

    test_log_trace "Cache reads before : $L_CACHE_READS_BEFORE"
    test_log_trace "Cache reads after  : $L_CACHE_READS_AFTER"
    if [ ${L_CACHE_READS_AFTER} != ${L_CACHE_READS_BEFORE} ]
    then
        test_log_trace "Unexpected reads from cache"
        return 1
    fi

    test_log_trace "Write 4k shall invalidet cached data, write on core only"
    # Write (Invalidate cached data)
    dd if=/dev/urandom of=${TEST_DEVICE} bs=4k count=1 oflag=direct

    # Sync
    sync && echo 3 > /proc/sys/vm/drop_caches

    # Get statistics
    L_CACHE_WRITES_BEFORE=$(get_stat_sectors_written ${CACHE_DEVICE}-part1)
    L_CORE_READS_BEFORE=$(get_stat_sectors_read ${CORE_DEVICE}-part1)
    L_CACHE_READS_BEFORE=$(get_stat_sectors_read ${CACHE_DEVICE}-part1)

    # Read file
    test_log_trace "Read 4k, read form core only"
    dd if=${TEST_DEVICE} of=/tmp/baba bs=4k count=1 iflag=direct

    # Sync
    sync && echo 3 > /proc/sys/vm/drop_caches

    # Get statistics
    L_CACHE_WRITES_AFTER=$(get_stat_sectors_written ${CACHE_DEVICE}-part1)
    L_CORE_READS_AFTER=$(get_stat_sectors_read ${CORE_DEVICE}-part1)
    L_CACHE_READS_AFTER=$(get_stat_sectors_read ${CACHE_DEVICE}-part1)

    test_log_trace "Core reads before : $L_CORE_READS_BEFORE"
    test_log_trace "Core reads after  : $L_CORE_READS_AFTER"
    if [ "$L_CORE_READS_BEFORE" == "$L_CORE_READS_AFTER" ]
    then
        test_log_trace "Expected reads from core"
        return 1
    fi

    test_log_trace "Cache writes before : $L_CACHE_WRITES_BEFORE"
    test_log_trace "Cache wrties after  : $L_CACHE_WRITES_AFTER"
    if [ "$L_CACHE_WRITES_BEFORE" != "$L_CACHE_WRITES_AFTER" ]
    then
        test_log_trace "Unexpected writes on cache"
        return 1
    fi

    # Sync
    sync && echo 3 > /proc/sys/vm/drop_caches

    test_log_trace "Resume cache"
    # Resume the cache
    CACHE_ID_OPTION="1" CACHE_MODE_OPTION="wt" set_cache_mode

    L_CACHE_WRITES_BEFORE=$(get_stat_sectors_written ${CACHE_DEVICE}-part1)
    L_CORE_READS_BEFORE=$(get_stat_sectors_read ${CORE_DEVICE}-part1)

    test_log_trace "Read 4k, read form core, write on cache"
    # Read file
    dd if=${TEST_DEVICE} of=/dev/null bs=4k count=1 iflag=direct

    # Sync
    sync && echo 3 > /proc/sys/vm/drop_caches

    L_CORE_READS_AFTER=$(get_stat_sectors_read ${CORE_DEVICE}-part1)
    L_CACHE_WRITES_AFTER=$(get_stat_sectors_written ${CACHE_DEVICE}-part1)

    test_log_trace "Core reads before : $L_CORE_READS_BEFORE"
    test_log_trace "Core reads after  : $L_CORE_READS_AFTER"
    test_log_trace "Cache writes before : $L_CACHE_WRITES_BEFORE"
    test_log_trace "Cache wrties after  : $L_CACHE_WRITES_AFTER"

    if [ "$L_CORE_READS_BEFORE" == "$L_CORE_READS_AFTER" ]
    then
        test_log_trace "Expected reads from core"
        return 1
    fi

    if [ "$L_CACHE_WRITES_BEFORE" == "$L_CACHE_WRITES_AFTER" ]
    then
        test_log_trace "Expected writes on cache"
        return 1
    fi

    return 0
}

#
# START TEST
#

test_log_start

run_cmd cache_suspend_init

run_cmd cache_suspend_test

run_cmd cache_suspend_deinit

test_log_stop

#
# END TEST
#

# Always return 0 at the end of the test - if at any point something has failed
# in the API functions, test will end and return a proper result.
# If you need to check other things during the test and end the test earlier, you
# should end the test using "end_test $retval" function
end_test 0
