name: Licence-date-verification
on: [push, pull_request]
jobs:
  verify-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.1

      - name: List all changed files
        run: |
          chmod +x .github/verify_header.sh
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            .github/verify_header.sh $file
          done
